spring:
  application: blog-luisjrz96
  config:
    activate:
      on-profile: dev
  main:
    banner-mode: off
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL}
    driverClassName: ${DRIVER_CLASS_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}